version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false
    volumes:
      - ../..:/workspaces:cached
    ports:
      - 8080:8080
    command: sleep infinity
