name: deploying to azure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: collage-events
  AZURE_RESOURCE_GROUP: 
  PACKAGE_PATH: Backend/target/*.jar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # step 1, checkout the branch and build .jar files
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: |
          echo "building backend"
          cd Backend
          mvn clean package -DskipTests
          echo "backend finish building"

      # step 2, login to azure
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        run: echo "done logging into azure"
      
      # step 3. configure azure app settings (for applications.properties)
      - name: configure azure app settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          app-settings-json: |
            [
              {"name":"SPRING_DATASOURCE_URL","value":"${{ secrets.DB_URL }}"},
              {"name":"SPRING_DATASOURCE_USERNAME","value":"${{ secrets.DB_USER }}"},
              {"name":"SPRING_DATASOURCE_PASSWORD","value":"${{ secrets.DB_PASS }}"},
              {"name":"SUPABASE_URL","value":"${{ secrets.SUPABASE_URL }}"},
              {"name":"SUPABASE_ANON_KEY","value":"${{ secrets.SUPABASE_ANON_KEY }}"},
              {"name":"SUPABASE_JWT_SECRET","value":"${{ secrets.SUPABASE_JWT_SECRET }}"},
              {"name":"SUPABASE_SERVICE_KEY","value":"${{ secrets.SUPABASE_SERVICE_KEY }}"}
            ]
      
      # step 4: deploying to app service
      - name: deply to app service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          package: ${{ env.PACKAGE_PATH }}

      