name: "Stage 2: Integration"

on:
  push:
    branches: [*]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:
  # Called by Stage 1 CI workflow completion
  workflow_call:
    inputs:
      sha:
        description: 'Commit SHA from Stage 1'
        required: true
        type: string
      ref:
        description: 'Git ref from Stage 1'
        required: true
        type: string
      stage1_run_id:
        description: 'Stage 1 run ID'
        required: true
        type: string
    secrets:
      POSTGRES_DB:
          required: true
      POSTGRES_USER:
          required: true
      POSTGRES_PASSWORD:
         required: true

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
  JAVA_VERSION: '21'
  DB_NAME: ${{ secrets.POSTGRES_DB }}
  DB_USER: ${{ secrets.POSTGRES_USER }}
  DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

jobs:
  integration-setup: 
    name: "Integration Infrastructure Setup"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Backend

    # PostgreSQL service container for integration testing
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 5432:5432
        # Fixed health check to use correct user
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    outputs:
      # Informs that infrastructure is ready if verify-infrastructure succeeds
      infrastructure-ready: ${{ steps.verify-infrastructure.outcome }}
      db-host: localhost
      db-port: 5432

    steps:
      - name: "Getting Code"
        uses: actions/checkout@v4
        with:
          # References the correct commit that passes Stage 1
          ref: ${{ github.event.client_payload.sha || github.sha }}

      - name: "Debug Repository Structure"
        run: |
          echo "Current working directory:"
          pwd
          echo ""
          echo "Contents of current directory:"
          ls -la
          echo ""
          echo "Looking for Backend folder specifically:"
          if [ -d "Backend" ]; then
            echo "✓ Backend folder exists"
            echo "Contents of Backend folder:"
            ls -la Backend/
          else
            echo "✗ Backend folder NOT found"
            echo "Searching for similar folders:"
            find . -maxdepth 2 -type d -iname "*backend*" 2>/dev/null || echo "No backend-related folders found"
          fi
        working-directory: .

      - name: "Debug Environment Variables"
        run: |
          echo "DB_NAME: '${{ env.DB_NAME }}'"
          echo "DB_USER: '${{ env.DB_USER }}'"
          echo "DB_PASSWORD length: ${#DB_PASSWORD}"
          echo "All environment variables that start with POSTGRES:"
          env | grep POSTGRES || echo "No POSTGRES variables found"
        env:
          DB_NAME: ${{ env.DB_NAME }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}

      - name: "Stage 1 Information"
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "==============================="
          echo " STAGE 2: INTEGRATION TESTING  "
          echo "==============================="
          echo "Triggered by Stage 1 completion"
          echo "Source SHA: ${{ github.event.client_payload.sha }}"
          echo "Source Ref: ${{ github.event.client_payload.ref }}"
          echo "Stage 1 Run ID: ${{ github.event.client_payload.stage1_run_id }}"
          echo "============================="

      - name: "Set up JDK 21"
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

      - name: "Install PostgreSQL client"
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: "Wait for PostgreSQL to be ready"
        run: |
          echo "Waiting for PostgreSQL service to be ready..."
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U $DB_USER; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting for PostgreSQL... (attempt $i/30)"
            sleep 2
          done
        env:
          PGPASSWORD: ${{ env.DB_PASSWORD }}

      - name: "Verify database connection"
        run: |
          echo "Testing database connection..."
          psql -h localhost -p 5432 -U $DB_USER -d $DB_NAME -c "SELECT version();"
          echo "Database connected!"
        env:
          PGPASSWORD: ${{ env.DB_PASSWORD }}

      - name: "Verify integration environment"
        run: |
          echo "Verifying integration environment setup..."
          java -version
          mvn -version
          echo "Integration environment ready!"
          echo "Note: Code compilation already verified in Stage 1"

      - name: "Check test configuration files"
        run: |
          echo "Checking for test configuration files..."
          if [ -f "src/main/resources/application-test.properties" ]; then
            echo "✓ application-test.properties found"
          elif [ -f "src/test/resources/application-test.properties" ]; then
            echo "✓ application-test.properties found in test resources"
          else
            echo "⚠ application-test.properties not found - will be created"
          fi

      - name: "Test database connectivity from application context"
        id: verify-infrastructure
        run: |
          echo "Testing database connectivity with application configuration..."
          
          # Create a temporary test to verify DB connectivity
          cat > src/test/java/TestDatabaseConnectivity.java << 'EOF'
          import java.sql.Connection;
          import java.sql.DriverManager;
          import java.sql.ResultSet;
          import java.sql.Statement;
          
          public class TestDatabaseConnectivity {
              public static void main(String[] args) {
                  try {
                      String url = "jdbc:postgresql://localhost:5432/" + System.getenv("DB_NAME");
                      String user = System.getenv("DB_USER");
                      String password = System.getenv("DB_PASSWORD");
                      
                      Connection conn = DriverManager.getConnection(url, user, password);
                      Statement stmt = conn.createStatement();
                      ResultSet rs = stmt.executeQuery("SELECT 1 as test");
                      
                      if (rs.next()) {
                          System.out.println("Database connectivity test - PASSED");
                      }
                      
                      rs.close();
                      stmt.close();
                      conn.close();
                  } catch (Exception e) {
                      System.out.println("Database connectivity test - FAILED: " + e.getMessage());
                      System.exit(1);
                  }
              }
          }
          EOF
          
          # Compile and run the connectivity test
          javac -cp "$(mvn dependency:build-classpath -q -Dmdep.outputFile=/dev/stdout):." src/test/java/TestDatabaseConnectivity.java
          java -cp "$(mvn dependency:build-classpath -q -Dmdep.outputFile=/dev/stdout):src/test/java" TestDatabaseConnectivity
          
          echo "Application-level database connected!"
        env:
          DB_NAME: ${{ env.DB_NAME }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}

      - name: "Infrastructure readiness check"
        run: |
          echo "Performing final infrastructure readiness check..."
          
          # Check PostgreSQL service health
          pg_isready -h localhost -p 5432 -U $DB_USER
          
          # Check disk space
          df -h
          
          # Check memory
          free -h
          
          # Check if Maven dependencies are cached
          if [ -d "$HOME/.m2/repository" ]; then
            echo "Maven cache is available"
          else
            echo "Maven cache not found - first run may be slower"
          fi
          
          echo "Infrastructure readiness check completed!"
        env:
          PGPASSWORD: ${{ env.DB_PASSWORD }}

      - name: "Infrastructure Setup Summary"
        run: |
          echo "=============================================="
          echo "        INFRASTRUCTURE SETUP COMPLETE         "
          echo "=============================================="
          echo ""
          echo "PostgreSQL 15 Service: Running on port 5432"
          echo "Database Connection: Verified ($DB_NAME)"
          echo "Java Environment: JDK 21"
          echo "Maven Setup: Dependencies cached"
          echo "Application Compilation: Successful"
          echo "Spring Boot Context: Ready for test profile (PostgreSQL for CI, H2 for local)"
          echo "Infrastructure Health: All systems operational"
          echo ""
          echo "Infrastructure Details:"
          echo "  - Database Host: localhost"
          echo "  - Database Port: 5432"
          echo "  - Database Name: $DB_NAME"
          echo "  - Database User: $DB_USER"
          echo "  - Spring Profile: test,ci to be used (PostgreSQL for true integration testing)"
          echo ""
          echo "=============================================="

  integration-tests:
      name: "Integration Tests"
      runs-on: ubuntu-latest
      needs: integration-setup
      if: needs.integration-setup.outputs.infrastructure-ready == 'success'

      defaults:
        run:
          working-directory: Backend

      # PostgreSQL service container for integration testing
      services:
        postgres:
          image: postgres:15
          env:
            POSTGRES_DB: ${{ env.DB_NAME }}
            POSTGRES_USER: ${{ env.DB_USER }}
            POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

      steps:
        - name: "Getting Code"
          uses: actions/checkout@v4
          with:
            ref: ${{ github.event.client_payload.sha || github.sha }}

        - name: "Set up JDK 21"
          uses: actions/setup-java@v4
          with:
            java-version: ${{ env.JAVA_VERSION }}
            distribution: 'temurin'
            cache: maven

        - name: "Create CI-specific test configuration"
          run: |
            echo "Creating CI-specific test configuration for PostgreSQL..."
            
            # Create a CI-specific properties file that will override the H2 settings
            TEST_CONFIG_DIR="src/test/resources"
            CI_CONFIG_FILE="$TEST_CONFIG_DIR/application-ci.properties"
            
            # Create directory if it doesn't exist
            mkdir -p $TEST_CONFIG_DIR
            
            # Create CI-specific configuration that uses PostgreSQL
            cat > $CI_CONFIG_FILE << EOF
            # CI-specific Test Database Configuration (PostgreSQL)
            spring.datasource.url=jdbc:postgresql://localhost:5432/$DB_NAME
            spring.datasource.username=$DB_USER
            spring.datasource.password=$DB_PASSWORD
            spring.datasource.driver-class-name=org.postgresql.Driver
            
            # Hibernate Configuration for PostgreSQL
            spring.jpa.hibernate.ddl-auto=create-drop
            spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
            spring.jpa.show-sql=true
            spring.jpa.properties.hibernate.format_sql=true
            
            # Server Configuration for CI
            server.port=0
            
            # Disable Flyway for tests - let Hibernate create schema from entities
            spring.flyway.enabled=false
            
            # Test Configuration
            logging.level.org.springframework.web=DEBUG
            logging.level.com.example.SummerBuild=DEBUG
            logging.level.org.springframework.security=DEBUG
            logging.level.org.springframework.boot.web.embedded.tomcat=INFO
            
            # Supabase Test Configuration (same as local)
            supabase.auth.url=\${SUPABASE_URL:http://localhost:54321}
            supabase.anonKey=\${SUPABASE_ANON_KEY:dummyAnonKey}
            supabase.jwtSecret=\${SUPABASE_JWT_SECRET:c3VwZXItc2VjcmV0LWp3dC10b2tlbi13aXRoLWF0LWxlYXN0LTMyLWNoYXJhY3RlcnMtbG9uZw==}
            supabase.serviceKey=\${SUPABASE_SERVICE_KEY:dummyServiceKey}
            
            # Bean override configuration
            spring.main.allow-bean-definition-overriding=true
            EOF
            
            echo "CI-specific test configuration created:"
            cat $CI_CONFIG_FILE
            echo ""
            echo "Local H2 configuration preserved in application-test.properties"
            
            # Show the difference
            echo ""
            echo "=== LOCAL vs CI CONFIGURATION ==="
            echo "Local (H2): Uses application-test.properties"
            echo "CI (PostgreSQL): Uses application-ci.properties"
            echo "================================="
          env:
            DB_NAME: ${{ env.DB_NAME }}
            DB_USER: ${{ env.DB_USER }}
            DB_PASSWORD: ${{ env.DB_PASSWORD }}

        - name: "Wait for PostgreSQL to be ready"
          run: |
            echo "Waiting for PostgreSQL service to be ready..."
            for i in {1..30}; do
              if pg_isready -h localhost -p 5432 -U $DB_USER; then
                echo "PostgreSQL is ready!"
                break
              fi
              echo "Waiting for PostgreSQL... (attempt $i/30)"
              sleep 2
            done
          env:
            PGPASSWORD: ${{ env.DB_PASSWORD }}

        - name: "Debug test environment"
          run: |
            echo "=== DEBUGGING TEST ENVIRONMENT ==="
            echo "Working directory: $(pwd)"
            echo "Java version: $(java -version 2>&1)"
            echo ""
            echo "Test configuration files:"
            find src -name "application*.properties" -o -name "application*.yml" 2>/dev/null || echo "No config files found"
            echo ""
            echo "Database connectivity test:"
            pg_isready -h localhost -p 5432 -U $DB_USER && echo "DB ready" || echo "DB not ready"
            echo ""
            echo "Available ports:"
            netstat -tuln | grep :8080 || echo "Port 8080 available"
            echo "=================================="
          env:
            PGPASSWORD: ${{ env.DB_PASSWORD }}

        - name: "Run Integration Tests"
          run: |
            echo "=============================================="
            echo "         RUNNING INTEGRATION TESTS            "
            echo "=============================================="
            echo ""
            echo "Database: PostgreSQL (localhost:5432) - Real integration testing"
            echo "Local Development: H2 in-memory (preserved)"
            echo "Spring Profiles: test,ci"
            echo "Infrastructure verified by previous job"
            echo ""
            
            # Run with both test and ci profiles
            # ci profile will override H2 settings with PostgreSQL
            mvn test \
              -Dspring.profiles.active=test,ci \
              -Dtest="EventAPIIntegrationTest" \
              -B
            
            echo ""
            echo "Integration tests completed successfully!"
            echo "=============================================="
          env:
            DB_NAME: ${{ env.DB_NAME }}
            DB_USER: ${{ env.DB_USER }}
            DB_PASSWORD: ${{ env.DB_PASSWORD }}

        - name: "Integration Test Results Summary"
          if: always()  # Run even if tests fail
          run: |
            echo "=============================================="
            echo "       INTEGRATION TEST RESULTS SUMMARY       "
            echo "=============================================="
            echo ""
            if [ -f "target/surefire-reports/TEST-*.xml" ]; then
              echo "Test reports generated:"
              ls -la target/surefire-reports/TEST-*IntegrationTest.xml 2>/dev/null || echo "No integration test reports found"
              
              # Show test summary
              echo ""
              echo "Test Results:"
              grep -h "tests=" target/surefire-reports/TEST-*IntegrationTest.xml 2>/dev/null | head -5 || echo "Could not extract test summary"
            else
              echo "No test reports directory found"
            fi
            echo ""
            echo "=============================================="

        - name: "Upload Test Reports"
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: integration-test-reports
            path: Backend/target/surefire-reports/
            retention-days: 30