name: Java Unit Tests

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven # Caches Maven dependencies

    - name: Run tests with Maven
      run: mvn -B test

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() # Always run even if the previous step fails
      with:
        report_paths: 'Backend/**/target/surefire-reports/TEST-*.xml'
